name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  primary:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: test
        run: npm run test

      # should save this keys in github, settings of the project, secrets :
      # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
      - name: aws deploy
        run: BUILD_DIRECTORY=build BUCKET_NAME=hpsportbucket AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} npm run deploy-aws
      #BUILD_DIRECTORY=build BUCKET_NAME=hpsportbucket AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} npm run deploy-aws
      #AWS Access Key: AKIAUCFZ3TWOFQHNM3UV
      #AWS Secret Access Key: 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
      #AWS S3 Bucket Name: hpsportbucket

